### ISSUE TITLE
Replaced image, but not updating

### ISSUE THREAD

**Issue by michaelmannucci** [spatie/statamic-responsive-images#103]
I have an image on my site. I made changes to it in photoshop and saved it (replaced the old file, same name, no changes to my code)... but my site is still showing the old image.

I've tried clearing Chrome's cache, I've tried `config:clear` and `cache:clear`... it still shows the old image.

How do I get it to show the new image?

**Comment by riasvdv** [comment]
There's a `php please glide:clear` command that you can try to clear the Glide cache

**Comment by michaelmannucci** [comment]
Thanks! That was it
