### ISSUE TITLE
@once @endonce Displaying Before Image

### ISSUE THREAD

**Issue by andrewcgregory** [spatie/statamic-responsive-images#108]
We're seeing an issue with the `@once @endonce` being output on our site. Looks like its coming from the file **vendor > spatie > statamic-responsive-images > resources > views > responsiveImage.blade.php**

[Screenshot of output](https://cln.sh/BL8oa9)

Statamic: 3.2.25
Responsive Images: 2.8.5

**Comment by riasvdv** [comment]
Does this still happen in 2.9.0?

**Comment by andrewcgregory** [comment]
Just tested on 2.9.1 and same result

**Comment by riasvdv** [comment]
Can't seem to reproduce this, can you share how you're using the addon in your templates?

**Comment by andrewcgregory** [comment]
Looks like we had an issue with something on the Statamic install (this site had originally been an updated site from an early Statamic v3 beta version). We did a fresh Statamic install and ported the site over and it resolved this issue.
