### ISSUE TITLE
Parse error during package:discover for version 2.11.0

### ISSUE THREAD

**Issue by taylorcammack** [spatie/statamic-responsive-images#112]
Hey, got this error while attempting to update to version 2.11.0. Any ideas? Running Statamic 3.3.1.

![Screen Shot 2022-03-21 at 1 56 05 PM](https://user-images.githubusercontent.com/2514935/159344733-bb39776c-4022-4ffa-933e-54c1f3f4392c.png)

**Comment by riasvdv** [comment]
Make sure you're using PHP 8
