### ISSUE TITLE
Latest commit not compatible with php7.4

### ISSUE THREAD

**Issue by brighttank** [spatie/statamic-responsive-images#113]
Hi,
The latest version of ResponsiveFieldType.php has the following code starting at line 181:
```
        $fields = $this->getFieldsWithValues($data);

        try {
            $processedFields = $fields->process();
        } catch (Throwable) {
            $processedFields = $fields;
        }

        return $processedFields
```
 
The catch (Throwable) { is not compatible with php 7.4

**Comment by bruceontheloose** [comment]
Can confirm I got the same error. (When trying to upgrade from 2.8.5 to 2.11.2 on PHP 7.4.2.) Will eventually upgrade PHP version, but wanted to pass this along.

**Comment by joho1968** [comment]
Got it here (obviously) also on PHP 7.4.x. Just out of curiosity, is this really a necessary construct? I mean, why not make it PHP 7+ compatible? Just curious.

**Comment by riasvdv** [comment]
Statamic itself requires PHP 8 now, we won't support 7.4 anymore https://github.com/statamic/statamic/blob/master/composer.json#L12
