### ISSUE TITLE
glide:width not applied to img src

### ISSUE THREAD

**Issue by tinusmile** [spatie/statamic-responsive-images#114]
glide:width is not applied to the image src, it is included in original size.

`{{ responsive:image glide:width="1600" }}`

`<picture>`
	`<source ... >`
	`<img alt="" src="/assets/image.jpg" width="2560"  height="1430" data-statamic-responsive-images>`
`</picture>`

Statamic 3.3.3 Pro
Laravel 8.83.5
PHP 8.1.2
spatie/statamic-responsive-images 2.11.0

Thanks!

**Comment by stuartcusackie** [comment]
I am noticing similar problems using the blade directive. glide:width and glide:height seems to be ignored:

`@responsive($image, ['glide:fit' => 'crop_focal', 'glide:width' => 400, 'glide:height' => 500, 'lg:glide:width' => 1368, 'lg:glide:height' => 410])`

Generated images are 337x224 and 1174x783. Width and height seems to be ignored. Ratios work a little better.
