### ISSUE TITLE
Class Responsive retrieveAsset method not returning Asset type in Statamic 3.3

### ISSUE THREAD

**Issue by Roberth91** [spatie/statamic-responsive-images#116]
I'm trialling an upgrade to Statamic 3.3 (from 3.2) and I've run into an issue where the retrieveAsset function in `src/Responsive.php` is breaking.

Starting line:57 

```
if ($assetParam instanceof Value) {
    $asset = $assetParam->value();

    if ($asset instanceof Collection) {
        $asset = $asset->first();
    }
}
```

Since 3.3 update this `$asset` can be an instance of `Statamic\Query\OrderedQueryBuilder` I had success when updating the code to the following:

```
if ($assetParam instanceof Value) {
    $asset = $assetParam->value();

    if (!$asset instanceof Asset) {
        $asset = $asset->first();
    }
}
```

**Comment by jmartsch** [comment]
I also got errors after upgrading to Statamic 3.3. 
After upgrading this error occurs on some pages with images (but not on all pages):
`Call to undefined method Statamic\Assets\OrderedQueryBuilder::extension()
E:\htdocs\dotnetic\website\resources\views/partials/sets/image.antlers.html#1`

My image.antlers.html file looks like this:
```
<figure>
  {{ image }}
    {{ responsive:image data-src="{{ url }}" glide:width="768" width="768"  class="{{ class ?? class ?? 'mx-auto' }} lazyload" placeholder="false" loading="lazy" decoding="async" }}
  {{ /image }}
  {{ if caption }}
      <figcaption class="block text-base text-gray-600 text-center max-w-sm mx-auto">{{ caption }}</figcaption>
  {{ /if }}
</figure>
```
The fix @Roberth91 provided solves this issue.
