### ISSUE TITLE
Undefined method error in Statamic 3.3.7

### ISSUE THREAD

**Issue by joseph-d** [spatie/statamic-responsive-images#121]
On Statamic 3.3.7 using a tag such as `{{ responsive:hero_image }}` results in the following error:

`Call to undefined method Statamic\Fields\Field::fillValue()`

The error goes away when the version is rolloedback to 3.3.6 and prior.

**Comment by imbwaldo** [comment]
Thanks for your post, @joseph-d. I experienced the same issue and you bailed me out!
