### ISSUE TITLE
Height calculated wrongly

### ISSUE THREAD

**Issue by codedge** [spatie/statamic-responsive-images#128]
I saw that in version 2.9.1 some correction for calculation of the height was done. Currently I am experiencing problems with calculation the correct heigth with a ratio of `1`.

As you can see each image got a different height although the width is always the same.

<img width="1586" alt="grafik" src="https://user-images.githubusercontent.com/4409904/166074083-9152ecd9-4ed0-4fd3-a864-8ca575ca28ea.png">

```
{{ responsive:image
    class="rounded main-image mx-auto" alt="{alt | sanitize }" title="{label | sanitize}" ratio="1.0"
}}
```

In version 2.8.5 everything works normal. From then on the issues appear.

Env:
- Statamic: 3.3.x
- PHP 8.1
- Responsive image: 2.11.2

**Comment by riasvdv** [comment]
I cannot seem to reproduce this, if you're still having this issue, please open a new one. Please also share the html output.
