### ISSUE TITLE
Pulling blueprint meta from image

### ISSUE THREAD

**Issue by tusamni** [spatie/statamic-responsive-images#13]
I'm trying to add EXIF data into the responsiveImageWithPlaceholder.antlers.html template, but am having issues.

Do I need to add a loop or something?

![image](https://user-images.githubusercontent.com/9271145/93495689-02166a00-f8d4-11ea-9f47-842e529505c5.png)

**Comment by riasvdv** [comment]
We only pass a few things to the template right now, not the full asset object

https://github.com/spatie/statamic-responsive-images/blob/master/src/Responsive.php#L78-L83

It's a good feature to add though, I'll add this soon so you have access to the full asset

**Comment by riasvdv** [comment]
You should now be able to access the asset data with `{{ asset }}` in the view
