### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by granttransition** [spatie/statamic-responsive-images#14]
Running responsive images results in 500 internal server error? I've install this add-on on three different sites and all result in the same error?

This is an example of code I am using…
```
{{ carousel }}
<div class="carousel-cell">
  {{
    responsive:carousel_photos
    ratio="16/9"
    title="{carousel_photos:image_title}"
    alt="{carousel_photos:alt}"
  }}
  <div class="overlay"></div>
    <div class="carousel-copy-wrapper">
      <div class="carousel-copy">
        <h1>{{ carousel_title }}</h1>
        <h2 class="h4">{{ carousel_text_copy }}</h2>
      </div>
  </div>
</div>
{{ /carousel }}
```
I've tried the following and nothing appears to change the above?
```
$ php please responsive:regenerate  
$ php please glide:clear  
$ php please static:clear

**Comment by felixstoessel** [comment]
I had the same issue. Reason was that WebP wasn't supported on my ImageMagick local install. Just add `webp="false"` to the tag.

**Comment by riasvdv** [comment]
What's the exact error you are getting?

**Comment by granttransition** [comment]
Sorry, I posted so long ago I changed my approach for images. I'll reload on a dev site and try again. Saying this, the error was as posted in the title

**Comment by riasvdv** [comment]
Closing for now, if it ever occurs again you can open a new issue
