### ISSUE TITLE
Ratio not generating when breakpoint starts with number

### ISSUE THREAD

**Issue by taylorcammack** [spatie/statamic-responsive-images#140]
Just noticed an issue where ratios aren't working when the breakpoint starts with a number (`2xl`, `3xl`, etc).

**Works:**

`{{ responsive:hero_image xl:ratio="4" }}`
`{{ responsive:hero_image xl2:ratio="4" }}`

**Doesn't work:**

`{{ responsive:hero_image 2xl:ratio="4" }}`

I've tried downgrading both the package and Statamic several versions. No dice. Any ideas?

**What I'm running**

```
Statamic 3.3.13 Pro
Laravel 9.17.0
PHP 8.0.18
aryehraber/statamic-captcha 1.8.0
doublethreedigital/duplicator 2.2.0
jonassiewertsen/statamic-livewire 2.9.0
rias/statamic-data-import 1.2.2
simonhamp/statamic-heroicons 1.0.1
spatie/statamic-responsive-images 2.12.3
webographen/statamic-dynamic-token 1.0.0
```

**Comment by ncla** [comment]
Could not reproduce this issue myself locally. Is the breakpoint specified in config/statamic/responsive-images.php? If the breakpoint is missing in config then it will not output on frontend.

**Comment by ncla** [comment]
Which Antlers version you are using? I am able to replicate this issue if `statamic.antlers.version` is set on `runtime`. Can you try setting it to `regex` if this is the case?
