### ISSUE TITLE
Asset data is not being hydrated correctly causing alt text to be filename instead

### ISSUE THREAD

**Issue by ncla** [spatie/statamic-responsive-images#143]
As requested, separate issue for the alt text issue. This is continuation of this issue. https://github.com/spatie/statamic-responsive-images/issues/74

I have created a minimal bug report repository to reproduce the issue. https://github.com/ncla/responsive-image-alt-bug-report

The steps are simple, for blank Statamic install:
1. Add responsive field to page blueprint
2. Upload image for responsive field on the "Home" page and save
3. Through assets browser, open the image you uploaded and edit the alt text
4. In home.antlers.html just do `{{ responsive:image }}`

You should see that the alt tag text is output from the filename itself.

The alt text is clearly saved, you can verify that through the asset .yaml file.

```
data:
  alt: "Don't believe his lies"
size: 706225
last_modified: 1656752941
width: 828
height: 563
mime_type: image/png
duration: null
```

Rias, let me know if you can reproduce this issue, if not I will try to adjust the repo to get it working.

**Comment by ncla** [comment]
What's very confusing to me is that a `$asset->meta()` dump in `ResponsiveTag` class does not contain asset data, while the same dump in `Responsive` class does contain the data.

`ResponsiveTag`
![image](https://user-images.githubusercontent.com/5507083/176998065-eba70434-6334-43ea-bd05-3e6e70f29683.png)
`Responsive`
![image](https://user-images.githubusercontent.com/5507083/176998043-fbc31144-057f-46e9-9347-ba2fec68d18d.png)
Dumps on the frontend
![image](https://user-images.githubusercontent.com/5507083/176998050-8bb85a6f-a216-422a-ac0b-3a67ea8d8fda.png)

Additionally in my opinion the current `it_uses_an_alt_field_on_the_asset` test should be rewritten (or a new test should be written) to hydrate asset data automatically from asset meta .yaml file, like in real scenario, and then assert if alt text matches.

**Comment by ncla** [comment]
I mean weirdly that one line fix in the #144 PR does it for me. I do not know how to write a test for it yet though. I see some examples for testing this sort of thing in statamic/cms repo https://github.com/statamic/cms/blob/3.3/tests/Assets/AssetTest.php#L422 but I couldn't get the tests to read the meta data from the .yaml file.

**Comment by ncla** [comment]
FYI for anyone checking this issue: [v2.12.4](https://github.com/spatie/statamic-responsive-images/releases/tag/v2.12.4) was published today with the fix, and one of the two folks in Discord server reported back and said that the fix in the PR fixed this issue.

**Comment by riasvdv** [comment]
Thanks for confirming, forgot to comment here about the release
