### ISSUE TITLE
Any way to use this plugin with inline `background-image: url(' ');`

### ISSUE THREAD

**Issue by michaelmannucci** [spatie/statamic-responsive-images#147]
Title is self-explanatory. Can I use this plugin with CSS's `background-image: url('');`? More specifically, with using tailwind: `bg-[url('')]`

**Comment by ncla** [comment]
I think this addon is too overkill if you just want a single image generated. What is the use case here? Why not just use regular Asset fieldtype and plain old Glide tag?
