### ISSUE TITLE
Errors with 'php please responsive:regenerate' don't tell you what image caused it

### ISSUE THREAD

**Issue by jeffwhitfield** [spatie/statamic-responsive-images#15]
Hi there! Just installed the add-on as part of a v2 to v3 upgrade. First run of the ``php please responsive:regenerate`` command resulted in a GD error of some sort. The problem is that the error doesn't tell me what image caused the error. As such, figuring out how to deal with it is more or less a matter of trial and error. Any way we can get an update so that errors are more informative?  :D

**Comment by riasvdv** [comment]
This should be improved in v1.3.2
