### ISSUE TITLE
Linking all fields inside "replicator"

### ISSUE THREAD

**Issue by bobevsky** [spatie/statamic-responsive-images#161]
When you use the "responsive" field inside a "replicator" in statamic, it connects all the instances together and this happens:

https://www.veed.io/view/6f384756-adf4-495e-9456-4f4276520ac4

**Comment by ncla** [comment]
Could you please reupload the video or provide steps how to reproduce? I saw the video but now it is archived. At the moment I am unable to replicate this bug, I have two identical sets with responsive field type but they do not update each other.

**Comment by bobevsky** [comment]
@ncla here's a new link to the video: https://vimeo.com/743887219

**Comment by ncla** [comment]
I am unable to reproduce this. Can you reproduce this issue on a clean CMS install with latest versions and if you can, provide a minimal reproducible repository?
