### ISSUE TITLE
this.name undefined when adding a new set in the middle of a replicator field

### ISSUE THREAD

**Issue by danielsmink** [spatie/statamic-responsive-images#186]
### Bug description

We use the responsive field to create sliders. We do so using a replicator field with a set containing a responsive field and text field for a title. When adding in a slide in the middle of the set of images the slide underneath is cleared from it's data and a error is shown in the console (see screenshot)

<img width="1399" alt="Screenshot 2022-12-08 at 20 29 51" src="https://user-images.githubusercontent.com/2118314/206549905-0ea465b4-b12e-40ed-9da8-6bb0624c05b6.png">

### How to reproduce

Create a blueprint with a replicator field with the set containing the responsive field. You can add new sets and remove them without any problem, but if you add a set in the middle (in between two sets) an error will occur. This is probably due to the publish fields not exposing their correct name. They seem to be stuck on the previous array index.

### Environment

```yaml
PHP 8.1.13
Laravel Framework 9.43.0
Statamic 3.3.60
Responsive images 2.14.4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by ncla** [comment]
Is this the error you are referencing?

![image](https://user-images.githubusercontent.com/5507083/206563157-4fa596f7-800d-498f-8602-b5d5408933e4.png)

Just checking but does this impact functionality for you? Editing, saving works fine for me even with the error.

I was only able to reproduce this error in console when deleting a set.

**Comment by danielsmink** [comment]
That's the one @ncla it impacts functionality if you add a slide/set in between two others. In that case it removes the data from the follow up slide as well. As they keep referencing the old array index number.

After I click the plus in the scenario underneath the data in that set will be gone as well.

<img width="1059" alt="Screenshot 2022-12-08 at 22 56 37" src="https://user-images.githubusercontent.com/2118314/206576031-8e67a2fa-299c-4712-8351-a1d461209d1c.png">

As you can see in the screenshot I've put the name in for debugging purposes and you can see the fields referencing the old array index.

<img width="1048" alt="Screenshot 2022-12-08 at 23 00 08" src="https://user-images.githubusercontent.com/2118314/206576533-44969ec3-74b1-40a6-8454-5cf5d6e662a3.png">

**Comment by el-schneider** [comment]
I can confirm having the exact same error. All data after the inserted set get's erased.

**Comment by el-schneider** [comment]
Maybe this got introduced with: https://github.com/statamic/cms/pull/7000

**Comment by ncla** [comment]
Possible. Can you try downgrading cms to version 3.3.51 which is one version before this PR to check if this issue introduced the bug? Thanks!

**Comment by danielsmink** [comment]
@ncla just tested with 3.3.51 same error occurs. The bug was reported to us by a client on October 27.

**Comment by el-schneider** [comment]
@ncla Thank you for looking into this!

My temporary workaround is to hide the in-between buttons, with some CSS 🤡

**Comment by danielsmink** [comment]
Thanks for the workaround @ncla that works for us!

**Comment by el-schneider** [comment]
> @ncla Thank you for looking into this!
> 
> My temporary workaround is to hide the in-between buttons, with some CSS 🤡

Just realized that it still allows my clients to duplicate or delete certain sets and wipe all following ones, so it's not really a great solution. Since I'm relying on breakpoints the other workaround also doesn't help me.

**Comment by el-schneider** [comment]
For anyone looking for a solution and as the `responsive` tag also lets you choose different fields per breakpoint I ended up doing this, using native asset fields and having a nice fallback if one stays empty:

```antlers
{{ base_image = image or image_desktop }}
{{ responsive:base_image :desktop:src="image_desktop"
```

**Comment by ncla** [comment]
Hey @el-schneider @danielsmink I have pushed a new release v2.15.1 that includes fix for this. Can you click around and see if it is fixed for you, and that there are no regressions?

**Comment by danielsmink** [comment]
Hi @ncla it works as expected! Great. Thanks so much.
