### ISSUE TITLE
Need to reauthorize this repo on the Statamic Marketplace

### ISSUE THREAD

**Issue by jackmcdade** [spatie/statamic-responsive-images#187]
### Bug description

We're getting unauthorized errors on this repo on the Marketplace (89k so far, nearly burning through our whole Sentry plan). Any chance you can see about reauthorizing?

### How to reproduce

N/A

### Environment

```yaml
N/A
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

Thanks! 😅

**Comment by ncla** [comment]
@riasvdv Could you take a look please? This is out of my reach.

**Comment by riasvdv** [comment]
@jackmcdade Should be fixed, sorry about that 😅 GitHub deleted all my authorizations

**Comment by jackmcdade** [comment]
Thank you!On Dec 12, 2022, at 5:54 AM, Rias ***@***.***> wrote:﻿
Closed #187 as completed.
