### ISSUE TITLE
Images no longer show a thumbnail preview after running 'php please responsive:regenerate'

### ISSUE THREAD

**Issue by janparkio** [spatie/statamic-responsive-images#20]
Images appear like this after installing Spatie/Statamic-responsive-images
After running 'php please responsive:regenerate' all the images on the Control Panel appear like the image below:

![Screen Shot 2020-12-03 at 18 02 42](https://user-images.githubusercontent.com/9617583/101088482-8f439380-3592-11eb-8cc6-be5ecd329ea8.png)

What could be the issue? How may I resolve it?

I'm running the site on my local machine and serving through Valet.

**Comment by riasvdv** [comment]
I haven't had this issue yet, but that command clears the full Glide cache, you can try running `php please assets:generate-presets` to see if that fixes the control panel previews.

**Comment by riasvdv** [comment]
I've added a new command: `responsive:generate` that doesn't clear the Glide cache, but just preloads the necessary responsive sizes. Running this instead should solve your issue
