### ISSUE TITLE
Blade Directive

### ISSUE THREAD

**Issue by FlorianMoser** [spatie/statamic-responsive-images#21]
Are there any plans on implementing a Blade directive, so the addon could be used with Blade templates?

**Comment by riasvdv** [comment]
Yes, planning to work on that soon, in the meantime, I've been using this helper:

```php
function responsive($asset, array $params = []): string
{
    $paramString = join('-', $params);

    if (! $asset instanceof \Statamic\Assets\Asset) {
        /** @var \Statamic\Assets\Asset $asset */
        $asset = $asset->value();
    }

    if (! $asset) {
        return '';
    }

    return cache()->rememberForever("responsive-{$asset->id()}-{$paramString}", function () use ($params, $asset) {
        /** @var \Spatie\ResponsiveImages\Responsive $responsive */
        $responsive = app(Responsive::class);
        $responsive->setContext([
            'url' => $asset->url(),
        ]);
        $responsive->tag = 'responsive:url';
        $responsive->setParameters($params);

        return $responsive->__call('responsive:url', []);
    });
}
```

Which allows you to use it like this in Blade:

```blade
{{ responsive($image, ['ratio' => '1']) }}
```

**Comment by FlorianMoser** [comment]
That's great news! I'm loving your addon.

Also thanks for the helper code!

**Comment by FlorianMoser** [comment]
Just wondering: currently I'm using the directives from [edalzell/statamic-blade](https://github.com/edalzell/statamic-blade), which returns everything as an array (also image assets). Sure, it's easy to tweak your helper to use arrays instead of objects. But how will you handle it in your addon? Or do you recommend another way to retrieve collection objects in Blade?

**Comment by riasvdv** [comment]
Added in 1.6.0 which allows you to do `@responsive($asset, ['ratio' => 1])` which just renders the image, just like the Antler tag
