### ISSUE TITLE
Strategy for manually loading images

### ISSUE THREAD

**Issue by andrew-ireland** [spatie/statamic-responsive-images#22]
Hi, first of all thank you for this amazing resource — it appears really well thought out. The strategy of using javascript to dynamically set sizes for responsive images is brilliant, and makes my life much better!

I wanted to ask whether there are any recommended strategies for updating the sizes/src not just on load, but also manually triggering this. For example; on a site some images may not be present in the 'Desktop' view, but are visible on 'Tablet/Mobile' views. If I resize the browser between these breakpoints, the Tablet/Mobile images will remain blurred until hard refreshing the browser. 

Are there any recommended methods I can use to update images when resizing in this way, or is it better for me to write my own script and handle it that way?

Thank you for any help/guidance you can provide,
Andrew

**Comment by riasvdv** [comment]
Personally I think this is a non-issue, mobile visitors won't suddenly change into desktop visitors. As for manually triggering the reload, you could probably write some JS to do this on page resize that loops over every image and re-runs this script:

```js
var imgWidth = this.getBoundingClientRect().width;
this.parentNode.querySelectorAll('source')
    .forEach(function (source) {
        source.sizes=Math.ceil(imgWidth/window.innerWidth*100)+'vw';
    });
```

You can find the script here https://github.com/spatie/statamic-responsive-images/blob/master/resources/views/responsiveImageWithPlaceholder.antlers.html

**Comment by andrew-ireland** [comment]
Thanks for your reply, I’ll look into doing that.

In my experience, often it can be an issue when changing orientation on a device (tablets/phones) moves between a breakpoint. When using visual breakpoints based on the sites’s design, rather than device widths this is a possibility.

**Comment by MadeByMike** [comment]
This is 100% an issue. You should just add the media attribute to the sources as is intended.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
