### ISSUE TITLE
Constraining image max-size (src in addition to srcset)

### ISSUE THREAD

**Issue by andrew-ireland** [spatie/statamic-responsive-images#23]
I'm trying to limit the generated sizes for images passing the 'glide:width' parameter. This sets a max-width for generated srcset items, but doesn't effect the src item (which pulls in the original high res image). 

In my use case, I'd like to be able to set a max width for the src element as well to avoid sending the original high res images and a large payload (optimising for Google lighthouse specifically). Is there a method you would recommend, or consider adding to optimise this fallback src?

Thanks again for your help 🙂

**Comment by riasvdv** [comment]
Could you check if the issue still persists in 1.7.1?
