### ISSUE TITLE
Setting width to graphql does nothing

### ISSUE THREAD

**Issue by SteJW** [spatie/statamic-responsive-images#233]
### Bug description

When I add a width to a GQL call, it basically does nothing. I still get all image sizes. When I need an of maximum 500px, it will still render everything with images of 1920px and more.

```
image {
        breakpoints {
          asset {
            id
            responsive(width: 450) {
              sources {
                srcSet
              }
            }
          }
        }
```

### How to reproduce

Add an image, try the GQL call and you'll see it doesn't change anything.

### Environment

```yaml
Statamic 4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

When I change this:

Use glide_width
```
image {
        breakpoints {
          asset {
            id
            responsive(glide_width: 450) {
              sources {
                srcSet
              }
            }
          }
        }
```

In ResponsiveGraphqlArguments we should add this to the $defaultBreakpointArgs:
```

            'glide_width' => [
                'type' => Type::int(),
            ],
```

I didn't want to create a pull request for this, because there is no logic in doing it like this because of the glideArgs.

**Comment by SteJW** [comment]
Any ideas?

**Comment by ncla** [comment]
If `glide_width` parameter works then use that for now. But yeah this looks like a bug. Not much else I can say without looking at this in depth, don't have much time on me right now.

**Comment by SteJW** [comment]
Ok, thanks!

**Comment by ncla** [comment]
Hey, try out v4.1.0 - should be fixed.

**Comment by SteJW** [comment]
Yes, thank you! It worked perfectly.
