### ISSUE TITLE
Github "About" and Composer Info shows wrong Statamic version

### ISSUE THREAD

**Issue by lakkes-ra** [spatie/statamic-responsive-images#247]
### Bug description

Hej, just notices that in your about, it's still saying "for Statamic 3". Was just confused as composer told me that when I ran `composer show`. 

![image](https://github.com/spatie/statamic-responsive-images/assets/63732644/95e7e53e-8d04-4b72-ba20-46a0b107cae1)

### How to reproduce

/

### Logs

```shell
/
```

### Environment

```yaml
/
```

### Installation

Other (please explain)

### Antlers Parser

regex (default)

**Comment by riasvdv** [comment]
Thanks, will be solved when we tag a new release
