### ISSUE TITLE
Crop_Focal doesn't seem to work

### ISSUE THREAD

**Issue by rileysiemens** [spatie/statamic-responsive-images#29]
I can't seem to get fit="crop_focal" to work.  Here is some example code of me inserting a photo using both the responsive tag and using glide:
```
{{ responsive:upcoming_block:background glide:fit="crop_focal" glide:height="256" glide:width="256" }}
<img src="{{ glide:upcoming_block:background fit="crop_focal" height="256" width="256" }}" alt="">
```

and here's the output:

![image](https://user-images.githubusercontent.com/23223158/103931638-3cf01800-50e6-11eb-9f57-d9c0db28537a.png)

As you can see, the top image isn't cropped at all (should be a square since I'm specifying identical width and height), and it's not fit to the image's focal point like it is in the second image.  Am I doing something wrong, or is it a bug?

**Comment by riasvdv** [comment]
The glide:width and glide:height parameters are used to set a *max* width & height, if you need a square image, use the `ratio` parameter.
