### ISSUE TITLE
Art Direction

### ISSUE THREAD

**Issue by aerni** [spatie/statamic-responsive-images#31]
A lot of times I need to display images in another aspect ratio depending on the screen size.

To do this, I hide/show the image depending on screen size:
```
{{ image }}
    {{ responsive:url width="1200" ratio="1/1" class="lg:hidden" }}
    {{ responsive:url width="1200" ratio="3/4" class="hidden lg:block" }}
{{ /image }}
```

I wonder if there might be a better approach to art direction, by adding the image in the desired aspect ratio to the correct source element: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#art_direction

I'm just thinking out loud. Maybe we can do something like this:
```
{{ image }}
    {{ responsive:url width="1200" ratio="1/1" lg:ratio="3/4" }}
{{ /image }}
```

This would create and add the correct image to the correct source element with a defined breakpoint. The breakpoints could be configurable in the addon's config and default to Tailwind CSS breakpoints.

**Comment by riasvdv** [comment]
I'd accept a PR that implements this 👍

**Comment by aerni** [comment]
Sweet! I'll see what I can put together.
