### ISSUE TITLE
True Art Direction

### ISSUE THREAD

**Issue by aerni** [spatie/statamic-responsive-images#33]
Now that we've got the ratio art direction going, I can't get my mind off true image art direction. This involves changing the image source based on screen size. An example could be, that you want to zoom into the image and change the focal point on mobile, and the default image on desktop.

You can see an example in the second image of [this demo](https://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/responsive.html).

And another example in [the hero of my website](https://michaelaerni.ch/en/work/hyve). Check out the mobile vs desktop breakpoint. The image changes.

We could even go as far as making it possible to pass glide parameters based on breakpoint too.

What do you think about this?

I'm happy to help you out with this.

**Comment by riasvdv** [comment]
Something like this would probably work as syntax:

```twig
{{ responsive:asset1 sm:asset2 glide:blur="10" sm:glide:blur="20" }}
```

I guess we'd need to parse for parameters that start with `sm:` specifically (the keys of the breakpoints config array) and group the parameters based on that. 

We could add an `$asset` and `$glideParameters` property on the `Breakpoint` class, and build the sources from the breakpoint instances as it works now.

If you're willing to do this then I welcome the help and PR :)

**Comment by aerni** [comment]
Yeah, something like that. I'm happy to take a look when I find some time.

Thinking from a practical perspective; how do you suggest dealing with an array of assets, where each asset in the loop should have breakpoint assets too? How would we do this in the Statamic CP?

The only way I can think of is an asset field to pick the main image. And then adding asset fields to the asset blueprint to be able to pick breakpoint assets when editing the image.

Then we could probably to something like this:

```
{{ assets:images }}
    {{ responsive:url :alt="alt" sm:asset_sm }}
{{ /assets:images }}
```

Does that make sense?

**Comment by riasvdv** [comment]
That does limit you to 1 set of art directed images per asset, can't mix & match but that might not be necessary anyway. 

A grid field could be a solution as well with an asset and dropdown selector for the breakpoint. Don't exactly know how you'd work with that in Antlers though (I'm only using Blade nowadays)

**Comment by riasvdv** [comment]
It might also be an option to create a fieldtype that handles this in this addon that then does everything when augmenting the data and you'd just to `{{ responsive_field }}` in your template, but I'd support the basic use case first.

**Comment by aerni** [comment]
> That does limit you to 1 set of art directed images per asset, can't mix & match but that might not be necessary anyway.

I'm not quite sure what you mean by this?

> A grid field could be a solution as well with an asset and dropdown selector for the breakpoint. Don't exactly know how you'd work with that in Antlers though (I'm only using Blade nowadays)

That sounds like a plausible option too. I'll tinker around with some ideas.

> It might also be an option to create a fieldtype that handles this in this addon that then does everything when augmenting the data and you'd just to {{ responsive_field }} in your template, but I'd support the basic use case first.

This would be dope! But that would probably be a very complex fieldtype. Let's do the basic first 😅

**Comment by aerni** [comment]
Alright, I've got a working draft going. I went with the following syntax. I chose `src` because that's what Statamic uses as well. e.g. for the Glide tag.

```php
{{ responsive:image lg:src="image_lg" }}

// You can also do this instead
{{ responsive src="image" lg:src="image_lg" }}
```

A question that came up is how to best deal with inheritance. Should larger breakpoints inherit everything from smaller breakpoints until something else is defined? Or should each breakpoint fall back to the default asset?

```php
```

**Comment by aerni** [comment]
Alright, I've got a working draft going. I went with the following syntax. I chose `src` because that's what Statamic uses as well, e.g. for the Glide tag.

```php
{{ responsive:image lg:src="image_lg" }}

// You can also do this instead
{{ responsive src="image" lg:src="image_lg" }}
```

A question that came up is how to best deal with inheritance. Should larger breakpoints inherit the asset, ratio, and glide params from smaller breakpoints until something else is defined? Or should each breakpoint fall back to the default asset, ratio, and glide params?

```php
// Default ratio is 1/1. From sm upwards will be 1/2.
// Or default ratio is 1/1. sm ratio is 1/2. Next breakpoint will be 1/1 again.
{{ responsive:image ratio="1/1" sm:ratio="1/2" }}
```

The first one feels more natural and fitting, as this is how media queries work too. What do you think?

**Comment by riasvdv** [comment]
Yeah I'd go the same route as media queries 👍

**Comment by aerni** [comment]
Man, this inheritance is giving me a headache. I have no idea how to tackle it. 🤔

**Comment by riasvdv** [comment]
Added in v2.1.0, let me know if you have any issues ;)

**Comment by aerni** [comment]
Man, you're on fire! Works like a charm. Now I'll have to check how you solved this 😅
