### ISSUE TITLE
Two Errrors:  "Failed parsing 'srcset' attribute value since it has an unknown descriptor." & "Dropped srcset candidate "\u003Cpicture\u003E""

### ISSUE THREAD

**Issue by TeckiAn** [spatie/statamic-responsive-images#35]
Dear Spatie Team, 

just trying out your amazing add on. So far its really great, just getting this error and I am not sure if the error is on my side or on your's...

**Comment by riasvdv** [comment]
Could you provide me with a bit more info on where this error happens? 

Searching for the error it could be a space in your asset's path that's causing this https://stackoverflow.com/a/36667434

**Comment by TeckiAn** [comment]
Sorry for answering late! I checked stackoverflow before so I assumed it was from your site. But indeed it was a fault from my site. Thanks a lot, its a great tool really appreciate! thx
