### ISSUE TITLE
Dynamic binding doesn't work

### ISSUE THREAD

**Issue by aerni** [spatie/statamic-responsive-images#36]
I've got an array of images. I want to output an image by its index.

**Data:**
```yaml
images:
  - image_1.jpg
  - image_2.jpg
  - image_3.jpg
```

**Template:**
```
// The single braces method works:
{{ responsive src="{images:0}" alt="{images:0:alt}" }}

// The dynamic binding method doesn't:
{{ responsive :src="images:0" :alt="images:0:alt" }}
```

I feel like the dynamic method should work too. It does with other Statamic tags.

**Comment by riasvdv** [comment]
Hmm all we do is get the param from Statamic like this https://github.com/spatie/statamic-responsive-images/blob/master/src/Tags/ResponsiveTag.php#L34 it should be parsed already 🤔

**Comment by aerni** [comment]
Yeah, I thought this might be a Statamic issue. I think it's [this one](https://github.com/statamic/cms/issues/2407).
