### ISSUE TITLE
Placeholder and Lazy Loading

### ISSUE THREAD

**Issue by aerni** [spatie/statamic-responsive-images#37]
I'm using the excellent [lazysizes](https://github.com/aFarkas/lazysizes) library to lazy load my images. I'm working with the [Low Quality Image Pattern](https://github.com/aFarkas/lazysizes#lqipblurry-image-placeholderblur-up-image-technique), which is pretty much what this addon is already doing with the placeholder.

But to make this work with lazysizes, I need access to the low-quality image in the view. I'm happy to PR this.

**Comment by aerni** [comment]
It's probably also a good idea to add the placeholder to the config. In most cases, you want the placeholder either created or not. Having to add `placeholder="false"` to every tag is very annoying. You could always override the global config on the tag level.

What do you think? I'm happy to help.

**Comment by FlorianMoser** [comment]
@aerni Funny, this is at least the fourth time you are looking for exactly the same solution at the same time as I am 😄 

I didn't know the lazysizes library, though. I was able to make it work with the responsive images plugin:

You can publish the plugin view using `php artisan vendor:publish --tag=responsive-images-views`. This creates the view `/resources/views/vendor/responsive-images/responsiveImage.blade.php`, which allows to use custom markup.

I quickly (and not so elegantly) changed the view to:

```
@foreach (($sources ?? []) as $source)
    @php($srcSetPieces = explode(' 32w, ', $source['srcSet']))
    <img
        {!! $attributeString ?? '' !!}
        data-sizes="auto"
        src="{{ $srcSetPieces[0] }}"
        data-srcset="{{ $srcSetPieces[1] }}"
        class="lazyload" />
@endforeach
```

It works, but I prefer the way the Statamic Responsive Images plugin handles the images. A native lazy loading option would be great.

But direct access to the variables would already help. It would also be nice to have `$attributeString` as an array. That way we could use the attributes to switch between different markup/layouts.

**Comment by riasvdv** [comment]
I've merged #38 which should allow you to do what you please ;)

**Comment by andrew-ireland** [comment]
> But direct access to the variables would already help. It would also be nice to have `$attributeString` as an array. That way we could use the attributes to switch between different markup/layouts.

I second this idea from @FlorianMoser. It would be great future enhancement to be able to conditionally switch the layout for lazy loading, or other things similar to how placeholders are handled. I.e. 'lazy="true"'.

If that attribute is present, you could then render a different layout like:

`@if($lazy ?? false) 
      data-src="{{ $src }}"
  @else
      src="{{ $src }}"
  @endif
`

**Comment by stuartcusackie** [comment]
Took me a while to figure this out but this seems to work pretty well in case anybody wants a shortcut.
I haven't bothered using data-sizes. Doesn't seem necessary...?

```
// All we have to do is add a 'lazyload' class exists on particular responsive image
@php($lazy = str_contains($attributeString, 'lazyload'))

<picture>
    @foreach ($sources ?? [] as $source)
        // Each source / media query can have a different sized placeholder
        @php($srcSetPieces = explode(' 32w, ', $source['srcSet']))

        @isset($source['srcSetWebp'])
            <source
                type="image/webp"
                @isset($source['media']) media="{{ $source['media'] }}" @endisset
                @if($lazy) lazy-srcset="{{ $source['srcSetWebp'] }}" srcset="{{ $srcSetPieces[0] }}" @else srcset="{{ $source['srcSetWebp'] }}" @endif
                @if($includePlaceholder ?? false) sizes="1px" @endif
            >
        @endisset

        <source
            @isset($source['media']) media="{{ $source['media'] }}" @endisset
            @if($lazy) lazy-srcset="{{ $source['srcSet'] }}" srcset="{{ $srcSetPieces[0] }}" @else srcset="{{ $source['srcSet'] }}" @endif
            @if($includePlaceholder ?? false) sizes="1px" @endif
        >
    @endforeach

    // No changes to original img tag ...
```
