### ISSUE TITLE
Blade Directives no longer working in 2.2.1

### ISSUE THREAD

**Issue by FlorianMoser** [spatie/statamic-responsive-images#43]
The Blade Directives stopped working in 2.2.1. The site build fails with "Class 'Spatie\ResponsiveImages\ResponsiveTag' not found".

The namespace of ResponsiveTag has changed and this should be reflected in the boot method of the ServiceProvider (line 79):

```
            return "<?php echo \Spatie\ResponsiveImages\Tags\ResponsiveTag::render({$arguments}) ?>";
```
instead of
```
            return "<?php echo \Spatie\ResponsiveImages\ResponsiveTag::render({$arguments}) ?>";
```

**Comment by riasvdv** [comment]
Ah, nice catch! I'll fix this soon

**Comment by riasvdv** [comment]
Fixed!
