### ISSUE TITLE
Fieldtype assets don't publish

### ISSUE THREAD

**Issue by aerni** [spatie/statamic-responsive-images#44]
I just did a fresh install. The `responsive.css` and `responsive.js` do not publish and I get a `Component responsive-fieldtype does not exist.` in the CP when including the fieldtype.

**Comment by patrikkernke** [comment]
Same here. But `php artisan vendor:publish` and choosing `statamic-responsive-images` fixed the issue for me.

**Comment by riasvdv** [comment]
Fixed in 2.4.1, I had publishing turned off because there weren't any assets in the past.
