### ISSUE TITLE
FR: Alt & Title defaults

### ISSUE THREAD

**Issue by goellner** [spatie/statamic-responsive-images#47]
Currently, we have to specify alt & title on every responsive image tag. 

It would be nice to set default fields. For example: we have on our asset blueprint `asset_title` and `asset_alt` defined. Since they are configurable it would be perfect to have a setting in the config, to set the two handles. If no title or alt is provided on the tag, it should use the defined values on the asset itself. If neither are set, then we don't have a title or alt defined.

Side note: we never use `title` as the handle for your asset title, as it falls back to the page title, if none is set

**Comment by riasvdv** [comment]
I'd suggest publishing the views and handling it that way. Adding more config options for this would bloat the addon a bit.
