### ISSUE TITLE
Limit selectable assets

### ISSUE THREAD

**Issue by goellner** [spatie/statamic-responsive-images#48]
The field doesn't limit to one asset in the stack selector and should be limited to one

**Comment by riasvdv** [comment]
Testing on my own site and assets are definitely limited to 1

**Comment by riasvdv** [comment]
Could you tell me how you're using the fieldtype?

**Comment by goellner** [comment]
Sure, you can still select all with the top left checkbox

**Comment by riasvdv** [comment]
I actually think that's a Statamic bug
