### ISSUE TITLE
Don't understand the ratio from documentation

### ISSUE THREAD

**Issue by falaeco** [spatie/statamic-responsive-images#49]
From the section Image Ratio of the read me, the example states that:

> `{{ responsive:image_field ratio="16/9" }}`
> 
> will apply a default ratio of 1/1. From breakpoint lg up to 2xl, the ratio will be 16/9. From 2xl up, the ratio will be 2/1. The breakpoints can be configured in the config and default to the breakpoints of Tailwind CSS.

Does this mean if I don't put anything, it will still apply a 1/1 for small, keep the original ratio for lg to 2xl, and a 2/1 for 2xl and up? If I wanted to keep the original ratio at any breakpoint, can I just deactivate the option in the YAML or does it simply remove the option in control panel?

Ideally I would like to use this add-on to generate different img size for different viewport to optimize loading while I personally take care of how they are being displayed in my templates.

**Comment by riasvdv** [comment]
I've updated the readme, the explanation was in the wrong place

https://github.com/spatie/statamic-responsive-images/commit/a50dc7b40f9b61a9cb2c9ddc1e209466b164ef28

**Comment by riasvdv** [comment]
If you only define 1 ratio, it will use that ratio for all breakpoints
