### ISSUE TITLE
Low-res images after update to 1.2.1

### ISSUE THREAD

**Issue by jmartsch** [spatie/statamic-responsive-images#5]
Images with glide worked fine before, but after updating to version 1.2.1 I only get low-res images displayed.
Reverting back to 1.2.0 fixes this problem.
Here is the code I use:
`{{ responsive:url glide:blur="20" glide:width="1024" alt="{title}" class="mx-auto"}}`
and this is the result

![msedge_2020-07-16_15-18-32](https://user-images.githubusercontent.com/551551/87675916-42445980-c778-11ea-8a61-633f6e336d20.jpg)

**Comment by riasvdv** [comment]
It seems like it looks low quality because of the `glide:blur="20"` or is that intended? 

Can you copy paste the generated html from the tag? Might give me more information on what goes wrong

**Comment by jmartsch** [comment]
Just re-checked this, and the error isn't occuring anymore, so I am closing this.. The blur was also not intended.
