### ISSUE TITLE
Uploaded images no longer selected after save + reload

### ISSUE THREAD

**Issue by stoffelio** [spatie/statamic-responsive-images#52]
I have a grid of responsive fields. When I add an image to one of them by uploading a new image, there is an error message in the console (see below). When I save and reload the page, said image is no longer selected in that responsive field, I have to select it again from the assets.

> vue.common.prod.js:6 TypeError: e.metaUpdated is not a function
>     at meta-updated (responsive.js:1)
>     at $e (vue.common.prod.js:6)
>     at a.n (vue.common.prod.js:6)
>     at $e (vue.common.prod.js:6)
>     at a.e.$emit (vue.common.prod.js:6)
>     at meta-updated (Field.vue?bee8:5)
>     at $e (vue.common.prod.js:6)
>     at a.n (vue.common.prod.js:6)
>     at $e (vue.common.prod.js:6)
>     at a.e.$emit (vue.common.prod.js:6)

This does not happen when I add an image that's already uploaded to the page.

**Comment by riasvdv** [comment]
Probably the same issue as #51
