### ISSUE TITLE
Images generated with responsive:generate are not being used

### ISSUE THREAD

**Issue by jeffwhitfield** [spatie/statamic-responsive-images#53]
I noticed that images generated with the responsive:generate command aren't being used at all. This is with v2.4.4.

I tested this by observing the generated images for a page that had just one image. 16 images were generated for this image by the responsive:generate command. After attempting to load the page, more images were generated and I ended up with 33 images in that same directory. Plus, the page errored with a 500 internal server error. Something is askew! 

I started to roll back the versions to see if I can find the culprit. I went back as far as v2.0.0 and the problem still existed. When I switched to v1.8.0 the problem went away. Only one extra image was created, which was a very small thumbnail (presumably for the control panel). All other images remained the same and the front-end used the images created by responsive:generate. So, yeah, something in v2.x was introduced that invalidates the images created by responsive:generate thus forcing the recreation of cached images. No bueno! :(

**Comment by riasvdv** [comment]
v2.5.0 released which should solve this
