### ISSUE TITLE
"Can't locate path" error on artisan vendor:publish

### ISSUE THREAD

**Issue by pryley** [spatie/statamic-responsive-images#6]
I get this error on a fresh install of Statamic 3 beta (3.0.0-beta.41)

![image](https://user-images.githubusercontent.com/134939/88997988-a4dc4000-d2b6-11ea-8914-b018e11e0502.png)

**Comment by riasvdv** [comment]
This should be fixed in the latest release (v1.2.2), it does not automatically publish anymore, and the publish itself works again.
