### ISSUE TITLE
Link to specific file for largest breakpoint

### ISSUE THREAD

**Issue by codedge** [spatie/statamic-responsive-images#61]
Hey,

I use this extension to display some smaller version of gallery images and want to link to the large file version when clicking on it. 

<img width="664" alt="grafik" src="https://user-images.githubusercontent.com/4409904/114309088-43779c80-9ae6-11eb-88a6-32f25d1c0699.png">

I use some [lightbox script](https://biati-digital.github.io/glightbox/) that requires the url to the large version of the image inside the `href` attribute. I'd like to use the generated `webp` version of one of the responsive images for that.

My code inside the view is this:

```html
{{ product_images }}
    {{ if !first }}
    <div>
        <a href="LINK TO FILE FOR LARGEST BREAKPOINT" class="glightbox" data-gallery="gallery1" >
        {{ responsive:image
        class="rounded gallery-image-thumb"
        alt="{alt | sanitize }"
        title="{label | sanitize}"
        }}
        </a>
        <div class="text-center mt-4">
            {{ view_description ?: label | sanitize }}
        </div>
    </div>
    {{ /if }}
{{ /product_images }}   
```

Is there a way to output the path/url for the largest breakpoint in my `<a href="...">`? I was thinking about something like `{{ responsive:image breakpoint="xl" no_tag="true" }}` to only get the url to the image.

**Comment by riasvdv** [comment]
You can just use `{{ url }}` which will link to the source image, which will always be the largest version

**Comment by codedge** [comment]
Using `{{ url }}` only outputs the current page I am on.

<img width="853" alt="grafik" src="https://user-images.githubusercontent.com/4409904/114309806-d1548700-9ae8-11eb-8180-0a5964037c6d.png">


```html
{{ product_images }}
    {{ if !first }}
        <div>
            <a href="{{ url }}" class="glightbox" data-gallery="gallery1" >
                        ...
            </a>
```

**Comment by riasvdv** [comment]
Hmm that should link to the asset, try `{{ image:url }}`

**Comment by codedge** [comment]
`{{ image:url }}` outputs nothing. This is the output of `{{ image | dump }}`

```php
array:6 [▼
  "src" => Statamic\Fields\Value {#2901 ▼
    #raw: "products/couchtische/couchtisch-paul/couchtisch-eiche-gebuerstet-massiv-holz-stahl-kufen-industrie-stil-3.jpeg"
    #handle: "src"
    #fieldtype: Statamic\Fieldtypes\Assets\Assets {#2903 ▶}
    #augmentable: null
    #shallow: false
  }
  "ratio" => Statamic\Fields\Value {#2851 ▶}
  "glide:fit" => Statamic\Fields\Value {#2891 ▶}
  "sm:glide:fit" => Statamic\Fields\Value {#2916 ▶}
  "md:glide:fit" => Statamic\Fields\Value {#2893 ▶}
  "lg:glide:fit" => Statamic\Fields\Value {#2936 ▶}
]
```

So there seems to be a proper src which the responsive image extention uses but to just get a normal link to the image, I am unable to do that.

**Comment by riasvdv** [comment]
Does `{{ image:src }}` work?

**Comment by codedge** [comment]
Thanks for the hint. I got it working by using `{{ glide src="{{image:src}}" }}`

**Comment by riasvdv** [comment]
Awesome!
