### ISSUE TITLE
Retrieve Single Image Source

### ISSUE THREAD

**Issue by intrepidws** [spatie/statamic-responsive-images#62]
Is it possible to retrieve the image source of a single image, given certain parameters (like height or width)? My use case is creating a carousel of logos using Alpine JS and I need to be able to define the URL of a single image, similar to this:

```
logos: [
    {
        'title': 'Avante',
        'url': '/images/logos/avante.png',
    },
    {
        'title': 'Cobalt',
        'url': '/images/logos/cobalt.png',
    },
    {
        'title': 'AT&T',
        'url': '/images/logos/att.png',
    },
]
```

**Comment by riasvdv** [comment]
If you're only retrieving a single image, I suggest just using the Statamic Glide tag, as you'll have no benefit of the responsive images and will only cause slower page loads
