### ISSUE TITLE
Loading Issues with Lots of Images

### ISSUE THREAD

**Issue by intrepidws** [spatie/statamic-responsive-images#63]
I am experiencing problems with images that never load on a page that shows close to 30 responsive images. You can see the page here:

https://new.archetypeconsulting.com/insights/learning-hub

This only seems to happen on pages with a lot of images (for instance I cannot get it to happen on a page with only 5 images). Additionally, I can only get it to happen in Chrome - well, at least not in Safari or Firefox). 

This _seems_ to be an issue with WebP but I cannot be certain of that. I have found a couple of things that seem to fix the issue, though I'm not entirely sure why they work.

1. Prevent WebP formats using `webp="false"`
2. Specifying a width using `glide:width="675"`

**Comment by intrepidws** [comment]
From further test, it would seem that this occurs even without a lot of images on the page. See this page for instance:

https://archetypeconsulting.netlify.app/case-studies/case-study-1/

**Comment by riasvdv** [comment]
v2.6.0 changes how the images are loaded a bit, could you update and see if that fixes your issue?

**Comment by intrepidws** [comment]
@riasvdv This seems to have fixed the problem, thanks for your help!
