### ISSUE TITLE
Almost identical (unnecessary) sources in the HTML output

### ISSUE THREAD

**Issue by mpskovvang** [spatie/statamic-responsive-images#64]
I tested the addon with a fresh Statamic installation and noticed the default fieldtype outputs 12 sources in the `picture` element when only uploading the default (required) image.

I would expect only two sources because the others are identical except the `media` attribute. It is just unnecessary bytes.

This happens because the `fit` parameter for each breakpoint is stored with the default `crop_focal` value when saving the entry.

The issue can be reproduced with:

```php
$responsive = new Responsive($this->asset, new Parameters([
    'glide:fit' => 'crop_focal',
    'sm:glide:fit' => 'crop_focal',
    'md:glide:fit' => 'crop_focal',
]));

$this->assertCount(1, $responsive->breakPoints()->toArray());
```

I was about to draft a PR, but I was unsure if you would prefer:

1. the `breakPoints` method to ignore breakpoints with parameters equal to the default parameters.
2. prevent the fieldtype from storing the default `crop_focal` value unless actual set by the user.

Let me know your thoughts and I'll be happy to submit a PR to this otherwise wonderful addon. 🙂

**Comment by riasvdv** [comment]
> prevent the fieldtype from storing the default crop_focal value unless actual set by the user.

We do want crop_focal to be applied by default though, so if you find a way to do this + have crop_focal still be the default then I'd prefer this and welcome a PR :)
