### ISSUE TITLE
Getting alt text from image asset

### ISSUE THREAD

**Issue by imbwaldo** [spatie/statamic-responsive-images#65]
I've added an image to Assets, given it some alt text (and saved it), and now want to pull that alt text into the rendered HTML. Here's my tag:

`{{ responsive:featured_image_responsive alt="{alt ?? title}" }}`

Unfortunately, it always renders the fallback title, the page title, which is not really what I want. I know the alt text is there on the asset itself – I find it in the meta YAML file. Am I doing something wrong?

(This is such a great Statamic addon, by the way. Thanks for creating it!)

**Comment by riasvdv** [comment]
Does `alt={featured_image_responsive:alt}` work?

**Comment by imbwaldo** [comment]
Thanks, @riasvdv, but that didn't work. All it gives me is the alt attribute:
<img width="287" alt="Screen Shot 2021-06-24 at 11 12 00 AM" src="https://user-images.githubusercontent.com/1582379/123312319-09ab1500-d4dd-11eb-90f9-898e947b5e31.png">

**Comment by stefankempf** [comment]
I have the same issue unfortunately. Did you @imbwaldo find a solution?

**Comment by imbwaldo** [comment]
Not yet, @stefankempf. But I haven't checked on this since the new version released on Friday …

**Comment by stefankempf** [comment]
I have updated and checked and yes, its working now.

`alt="{{ image:alt ?? title }}"`

Great 🧡

**Comment by imbwaldo** [comment]
That's great news! Thanks for letting me know.
