### ISSUE TITLE
Images not rendering when called twice on a page?

### ISSUE THREAD

**Issue by imbwaldo** [spatie/statamic-responsive-images#68]
I have a page and, at screen sizes 1024px and up, the image appears in the sidebar. Below 1024px, the same image is set to appear at the top of the page. What I'm seeing is if the page is loaded at 1024+, the sidebar image pops in and is nicely rendered:

![Screen Shot 2021-06-28 at 3 14 57 PM](https://user-images.githubusercontent.com/1582379/123710534-caa1fa00-d823-11eb-9cd0-090694d26486.png)

Narrow the browser window down below 1024px, however, to where the image should appear at the top (and a different aspect ratio), and I get only a preview image (blurred beyond recognition):

![Screen Shot 2021-06-28 at 3 15 18 PM](https://user-images.githubusercontent.com/1582379/123710575-d7bee900-d823-11eb-83a5-332a34a506af.png)

The reverse is true: load the page in a narrow browser window (under 1024px) and the header image pops in neatly, but expand the browser out to 1024px and that image appears in the sidebar as a preview only.

Is this happening because I'm essentially calling the same image twice on a single page, only hiding it in one place and revealing it in another, depending on the browser width? If so, is there a way to get Responsive Images to render both images correctly? Or is this likely something else entirely?

**Comment by riasvdv** [comment]
Please try v2.6.0 as we've made some changes to how images are loaded.
