### ISSUE TITLE
Zero byte image causes generate command to fail

### ISSUE THREAD

**Issue by mikemartin** [spatie/statamic-responsive-images#71]
After much investigation it turns out my client had uploaded some corrupt (zero byte) images which caused the generate command to fail. See error and screenshot below.

Error:
```
  722/1592 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  45%
   ErrorException 

  Division by zero

  at vendor/spatie/statamic-responsive-images/src/Responsive.php:76
     72▕         $parametersByBreakpoint = $this->parametersByBreakpoint();
     73▕ 
     74▕         $defaultParams = $parametersByBreakpoint->get('default') ?? collect();
     75▕         $currentParams = array_merge([
  ➜  76▕             'ratio' => $this->asset->width() / $this->asset->height(),
     77▕             'src' => $this->asset,
     78▕         ], $defaultParams->mapWithKeys(function ($param) {
     79▕             return [$param['key'] => $param['value']];
     80▕         })->toArray());
  ```
  
  screenshot:
  
<img width="1383" alt="Screen Shot 2021-07-02 at 4 07 32 pm" src="https://user-images.githubusercontent.com/414211/124228624-cc372f00-db4f-11eb-9e78-5ea118ff8c6a.png">

**Comment by riasvdv** [comment]
Are you on the latest version of Statamic? It seems like there's something about zero byte images in the changelog https://github.com/statamic/cms/releases/tag/v3.1.27

I'm torn on whether we should check if width & height are 0 before doing anything, because this is something you might want to fail.

**Comment by riasvdv** [comment]
We'll add a custom exception when width and/or height are 0 with the asset that has the issue to track it down more easily
