### ISSUE TITLE
Using Responsive field type within a replicator causes an error

### ISSUE THREAD

**Issue by markdavies** [spatie/statamic-responsive-images#73]
https://flareapp.io/share/LPdXEMpP?error=LPdXEMpP&owner_token=aawrkZw0qXkYiqxP98iCj3uPBTSTvhUw#F86

`Undefined index: container in vendor/spatie/statamic-responsive-images/src/Fieldtypes/ResponsiveFields.php:60`

**Comment by riasvdv** [comment]
Make sure you set a container in the blueprint for the field
