### ISSUE TITLE
Please add support for lazyloading

### ISSUE THREAD

**Issue by jmartsch** [spatie/statamic-responsive-images#8]
Most lazyloading scripts like lazysizes require to have a `data-src` attribute and an empty `src` attribute, or a placeholder/low-res image in the src.

Right now, the src attribute is always printed out, and prevents the lazyloading.

To keep the code compatible with most lazyload libraries my thoughts for the template are:
`{{ responsive:url src="" data-src="{{ url }}" glide:width="1024" alt="{title}" class="lazyload" placeholder="false" }}`

So if the `src` param is provided in the tag, then it would not be overwritten by the output of the module. This would even allow us to use a custom placeholder image like from placehold.it

`{{ responsive:url src="https://via.placeholder.com/150" data-src="{{ url }}" glide:width="1024" alt="{title}" class="lazyload" placeholder="false" }}`

Could you please consider adding support for this? I will provide more information if you need.

**Comment by jmartsch** [comment]
It would be even better if a placeholderURL tag would be provided, so that we could use 
`{{ responsive:url src="placeholderURL" data-src="{{ url }}" glide:width="1024" alt="{title}" class="lazyload"}}`

This could also open up new possibilities like using the great [blurHash library](https://github.com/woltapp/blurhash) for low-res previews of the images

**Comment by riasvdv** [comment]
You can publish the view files using

```
php artisan vendor:publish
```
and choosing `Spatie\ResponsiveImages\ServiceProvider`

And decide yourself how the addon should render its tags. I'd like to keep the purpose of this addon pretty simple and straightforward.

**Comment by jmartsch** [comment]
Thanks for your answer, but publishing seems to fail here:

Can't locate path: <0>
Can't locate path: <1>

![image](https://user-images.githubusercontent.com/551551/89421562-7c2fcc80-d734-11ea-8039-164bb87e377f.png)
I am on Windows 10

Any idea what I can do? can I copy the files by hand? Or where do I find the published files afterwards? In the public/views/ folder!?

**Comment by riasvdv** [comment]
Are you on version 1.2.2? That version contains a fix for it, I mistagged it so you might have to run `composer update`

**Comment by jmartsch** [comment]
The latest version, that packagist reports is 1.2.1. See https://packagist.org/packages/spatie/statamic-responsive-images
So I can't install 1.2.2 via composer!?

**Comment by riasvdv** [comment]
I've updated packagist, it should show now

**Comment by jmartsch** [comment]
Hello @riasvdv. The update to 1.2.2 and publishing worked fine.
But modifying the HTML does not help because the src attribute is always inserted, even if I set it to empty.

Here is the code I use
```<figure>
        {{ image }}
            {{ if extension !== 'gif' }}
                {{ responsive:url src="" data-src="{{ url }}" glide:width="768" alt="{alt}" class="{class} mx-auto lazyload" placeholder="false" }}
            {{ else }}
                <picture>
                    <img src="{{ url }}" alt="{title}" class="mx-auto lazyload">
                </picture>
            {{ /if }}
        {{ /image }}
    {{ if caption }}
        <figcaption class="block text-base text-gray-600 text-center max-w-sm mx-auto">{{ caption }}</figcaption>
    {{ /if }}
</figure>
```

and here is the resulting source code (only the relevant part):
```
 <img
        src="" data-src="/assets/referenzen-startseite.png" alt="" class=" mx-auto lazyload"
        src="/assets/referenzen-startseite.png"
        width="565"
        height="596"    >
```

because the empty src attribute is overwritten by the second one, lazyloading is not possible.

Could you please re-open this issue and add support for this?

Cheers
Jens

**Comment by jmartsch** [comment]
Hello @riasvdv. The update to 1.2.2 and publishing via `php artisan vendor:publish` seem to work fine. The files were copied.
But modifying the HTML in public/views/vendors/responsiveImage.antlers.html does not work. I only wrote the word "test" into this file but still get the normal default output instead of "test"

Any hints?

Cheers
Jens

**Comment by riasvdv** [comment]
Might be something wrong with how the views are loaded, I'll check it out as soon as I can, could you create a new issue for this?

**Comment by pryley** [comment]
For native lazy loading, all that is needed is to add the following attribute to the img tag:
`loading="lazy"`.

See: https://web.dev/native-lazy-loading/

**Comment by jmartsch** [comment]
Although native lazy-loading is a simple solution, it is not necessarily the best. For example, if you want to offer a preview image with blur-up technology, or another treshold that cannot be controlled with the native solution, and is handled differently by all browsers.

But at least it is a possibility to use the native loading="lazy".
