### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'observe')

### ISSUE THREAD

**Issue by taylorcammack** [spatie/statamic-responsive-images#89]
Having an issue with the homepage hero image not loading on the production server. Loads fine locally.

![Screen Shot 2021-09-27 at 3 08 18 PM](https://user-images.githubusercontent.com/2514935/134977800-226c7f88-ddff-4969-82b5-d019a659d9c9.png)

Throws this error:
```
(index):405 Uncaught TypeError: Cannot read properties of undefined (reading 'observe') at HTMLImageElement.onload ((index):405)
```

And the markup:

![Screen Shot 2021-09-27 at 3 06 33 PM](https://user-images.githubusercontent.com/2514935/134978046-e06388ed-bc78-4095-a4d4-1eb29061b8f7.png)

I removed the responsive ratios and still having the same issue. Any ideas on where to start?

**Comment by lakkes-ra** [comment]
We found a quite but not 100 percent similar issue. You can find it here: #90 
In our case it had something to do with `tailwindcss` and the new `ResizeObserver` used from version 2.6. For us it worked to downgrade to version 2.5.5 for now.

**Comment by taylorcammack** [comment]
Thank you, it worked for us as well. 👍
